### ISSUE TITLE
Typo - "You have dug *throug* the rubble."

### ISSUE THREAD

**Issue by ghost** [ktchernov/Dig-Deep-RL#1]
Tiny typo- when you dig through rubble, the log says that you've dug "throug" the rubble. Here's a screenshot: 
![typo](https://cloud.githubusercontent.com/assets/5707110/7448020/7c3b8324-f1dc-11e4-9d02-11a7bdfad1da.png)

Just thought I'd let you know. :)

**Comment by ktchernov** [comment]
Thanks!

Fixed and updated the site.
